# Configuration File for CoreExtensions
# Settings
settings:
  ALLOW_EXISTING_REGISTRY_RELOADING: true
  ALLOW_RELOADING_REGISTRY: true
  AUTO-REPLACE_RELOADING_REGISTRY_BLOCKS: false
  CHECKING_FOR_UPDATE: true
  ENABLED_CORE_API: true
  ENABLED_OLD_CORE_API: false
  ENABLED_DATAGEN_EXPORT: true
  ENABLED_DEBUG: false
  FEATURE_ENABLE: true
  FEATURE_MOON: true
  FEATURE_AETHER: true
  FEATURE_ITEMSADDER: true
  FEATURE_GAMETEST: true
  FIX_POTION_GLOWING: true
  CONFIG_VERSION: 1